# 项目名称
appName: vboot

vboot:
  adminUserName: admin  # 一个管理系统只有一个admin账号，也是最高权限


server:
  servlet:
    context-path: /
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30


spring:
  resources:
   static-locations: file:/
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.180.240:3307/vboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 开启监控sql
          enabled: true
          # 显示并标注慢sql 默认当超过3秒显示
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        # 防SQL注入过滤
        wall:
          config:
            # 允许多条sql同时执行
            multi-statement-allow: true
  # Redis
  redis:
    # 超时时间 Duration类型 5秒
    timeout: 5s
    host: 120.78.180.240
    password: vboot123456
    # 数据库索引 默认0,如果多个项目，配置不同的database不会冲突
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 1


  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # 时间处理
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  # admin监控 https://blog.csdn.net/forezp/article/details/86105850
  boot:
    admin:
      # 修改上下文路径
      context-path: /admin
      client:
        url: http://127.0.0.1:${server.port}/admin
        # 配置实例地址
        instance:
          health-url:  http://127.0.0.1:${server.port}/actuator/health
          service-url: http://127.0.0.1:${server.port}
          management-url: http://127.0.0.1:${server.port}/actuator



# MBP配置文件
mybatis-plus:
  mapper-locations: classpath*:dao/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: del_flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      update-strategy: IGNORED # 所有字段都更新和插入

# redis配置
redis:
  unit: day
  time: 15



# token交互方式
token:
  # 默认为true，token将存入redis，并具有单点登录功能 设为false使用JWT交互
  redis: true
  # 是否开启单设备登陆 仅当token交互方式为redis时生效
  sdl: true
  # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
  storePerms: true
  # token过期时间（分钟）
  tokenExpireTime: 1200
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10


ignored:
  # 无需登录认证的请求
  urls:
  - /oauth2/**
  - /actuator/**
  - /admin/**
  - /editor-app/**
  - /act/**
  - /dictData/getByType/**
  - /email/sendResetCode/**
  - /email/resetByEmail
  - /file/view/**
  - /social/**
  - /ws/**
  - /logout
  - /security/login/page
  - /user/regist
  - /user/smsLogin
  - /user/resetByMobile
  - /security/**
  - /druid/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /swagger/**
  - /doc.html
  - /**/v2/api-docs
  - /webjars/**
  - /**/*.js
  - /**/*.css
  - /**/*.png
  - /**/*.ico
  - /test/**
  - /code/fileDownLoad
  - /user/findMenuAndPerByUsername   #根据用户名获取权限和菜单
  # 限流及黑名单不拦截的路径
  limitUrls:
  - /**/*.js
  - /**/*.css
  - /**/*.png
  - /**/*.ico

# Swagger界面内容配置
swagger:
  title: VBoot API接口文档
  description: VBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://www.kancloud.cn/exrick/xboot/1009234
  name: Carson
  url: https://www.kancloud.cn/exrick/xboot/1009234
  email: 598220654@qq.com


# 配置打印sql语句
logging:
  level:
    com:
      carson:
        vboot:
          core:
            dao: DEBUG
          generator:
            dao: DEBUG

# 代码文件生成存放地址
code:
  winPath:   H:\
  linuxPath: /usr/local/java/vboot/vboot/vboot-admin/target/classes
